### ISSUE TITLE
[Feature] Fusion Mags, Self-Reloading Energy Weapons

### ISSUE THREAD

**Issue by Beanzilla** [natelastname/ctf_guns#8]
## What is it?

An optional upgrade can be performed on energy weapons, simply by adding an additional Energy gun part (`ctf_ranged:gunparte`) to the already made energy Weapon (Perhaps only allowing a unloaded energy weapon to be upgraded).

## What it does?

While the gun is loaded and in the players inventory it will reload (this done by repairing the item since that's the "magazine" status) every second. (This causes energy weapons to appear to reload, yet another pro for energy weapons)

> A con would/could be it only reloads loaded fusion energy weapons, unloaded must be loaded manually with a energy ammo pack.

## To-Do

- [ ] Build a unloaded and loaded variant of the energy weapons (all these being the fusion versions)
- [ ] Ensure that the loaded will switch to the unloaded fusion weapon. (And that the unloaded switches to the loaded when feed a energy ammo pack)
- [ ] Use a globalstep with a interval of 1 second to achieve fusion mag reloading.
- [ ] Release it as PR `Fusion Mags`.

## Optional To-Do

> Things here are ideas and subject to change (Might not happen)

- [ ] Increase all energy weapons fire rates by at least 25%. (I personally feel the energy rifle fires too slowly, for it being automatic, I'm actually thinking 25% or possibly even 35% fire rate increase for the energy rifle, the other energy weapons also seem to shoot slowly, which in my opinion is contradictory, energy weapons have little to no recoil, as they are not firing matter but energy, so it should fire faster)

### Back burner

> Things here are ideas concepts we talked about a while ago that haven't been done yet (Need to do them at some point)

- I said I would look into the rawf ray trace for energy weapons making that slower than normal guns. (I've yet to do that, mostly been burned out on coding, time to get back to it though)

**Comment by Beanzilla** [comment]
## Settings

- [ ] `ctf_guns.allow_energy_fusion` (boolean) If true then we support making the recipes to upgrade energy weapons, else only by give or a shop can it be obtained (as a separate item), default's to true. (Copies the other settings on limiting crafting)
- [ ] `ctf_guns.fusion_reload_speed` (int) This will actually be a percent a fusion mag will reload by. (E.G. setting this to 5 means it will repair all fusion weapons by 5% of their durability, which is fast), default's to 1. (1% per second isn't fast, but isn't to slow either)

> Forgot about the new settings.

**Comment by Beanzilla** [comment]
The provide PR does not increase the fire rates for energy weapons or fusion energy weapons. (Only adds Fusion Energy weapons)
